### ISSUE TITLE
Isn't it a good time to convert to Typescript for Angular 6?

### ISSUE THREAD

**Issue by ccpony** [neodynamic/JSPrintManager#1]

**Comment by neodynamic** [comment]
Thanks for the feedback. We've just published a declaration file which can be found under the js folder of the repo. HTH

**Comment by lilian131** [comment]
@neodynamic hi please can you reference to the typescript file ? I could not find it

**Comment by neodynamic** [comment]
https://github.com/neodynamic/JSPrintManager/tree/master/scripts
