### ISSUE TITLE
.d.ts type definnation is not working with typescript import

### ISSUE THREAD

**Issue by hiepxanh** [neodynamic/JSPrintManager#10]
```
import { Injectable } from '@angular/core';
import * as JSPM from 'jsprintmanager';


@Injectable({providedIn: 'root'})
export class PrinterManagerService {
  constructor() {  }

  silentPrint() {
    console.log('JSPM', JSPM);
    console.log('jsprintmanager', JSPM.JSPM);
    JSPM.JSPrintManager.auto_reconnect = true;
    JSPM.JSPrintManager.start();
    JSPM.JSPrintManager.WS.onStatusChanged = async () => {
      if (JSPM.JSPrintManager.websocket_status === JSPM.WSStatus.Open) {
        const list = await JSPM.JSPrintManager.getPrinters();
        console.log('list', list);
      }
    };
  }

}

```
I just wonder why?

![image](https://user-images.githubusercontent.com/16970990/77245400-f01f7b80-6c50-11ea-8f4d-b5335f8bacd2.png)

**Comment by neodynamic** [comment]
What happens if you replace `import * as JSPM from 'jsprintmanager';` by `import {JSPM}  from 'jsprintmanager';`

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/77318104-0c014b00-6d3f-11ea-94ad-8c064d5d6104.png)
here you are

**Comment by neodynamic** [comment]
What exact version of JSPrintManager.js are you referencing?

**Comment by hiepxanh** [comment]
[image: image.png] 2.0.4 sir

Vào Th 3, 24 thg 3, 2020 vào lúc 21:13 Neodynamic Dev Team <
notifications@github.com> đã viết:

**Comment by neodynamic** [comment]
May you try using the **d.ts** file in **@types/jsprintmanager**?

`npm i @types/jsprintmanager`

**Comment by hiepxanh** [comment]
close this issue still I use everything I can try and look like we cannot resolve. Includes `npm i @types/jsprintmanager` but it not work!!!!!!!!!!!!!!!
I used to with typescript for 5 years bro. I know it the first thing I try. So if I'm not use  `npm i @types/jsprintmanager` => the vscode was show error everywhere if I'm using JSPM and I cannot `import { JSPM } from 'jsprintmanager'`

**Comment by neodynamic** [comment]
We've just created a sample Angular app using JSPrintManager for your reference https://github.com/neodynamic/JSPrintManager-Angular

**Comment by go2theG** [comment]
@neodynamic is there no better way than coyping your source code into our package? Why ist there a npm package if we have to copy the source code into our code base.

**Comment by sushil1991** [comment]
@neodynamic Can you provide the solution by using the **npm i @types/jsprintmanager**
We already have the **npm** so I did not understand why still we have to copy the source code into our codebase.
