### ISSUE TITLE
Auto start with Operating System

### ISSUE THREAD

**Issue by ihussain1024** [neodynamic/JSPrintManager#11]
JSPrintManager should auto start with OS power on. But it is not happening. Successfully printed barcode, but every time (when OS start) , have to start JSPrintManager. Is there any way to do that ?

**Comment by neodynamic** [comment]
JSPrintManager should auto start after each OS power on... What OS is involved there?

**Comment by ihussain1024** [comment]
Linux Mint 19.1 Cinnamon. It does not auto start after power on.

**Comment by neodynamic** [comment]
Please do the following

1. Verify that the following file exists `/etc/xdg/autostart/jspmd2.desktop` and that it contains the following: 

[Desktop Entry]
Type=Application
Name=JSPrintManager Daemon
Exec=/usr/bin/JSPMDaemon2 -r
Terminal=False

2. In addition, verify if the JSPMDaemon2 appears in the [Startup Applications](https://winaero.com/blog/manage-startup-apps-linux-mint/)

**Comment by ihussain1024** [comment]
I have checked. It is there exactly as you said. And also I have checked in Startup Application. It is there too. But till not working. Then I have increased delay time to 10 seconds in Startup Application. Now it is working. Thank you for your valuable reply. Really appreciated.👌👌👌
