### ISSUE TITLE
How to start JSPM3 on Linux/Ubuntu 20.04?

### ISSUE THREAD

**Issue by ahsath** [neodynamic/JSPrintManager#12]
Hi folks!

I downloaded the JSPM Client App for Linux and try to use the [demo app](https://jsprintmanager.azurewebsites.net/), restarted my browser and this message keep appearing no matter what browser I'm using

> It seems that JSPM Client App is not installed or not running in this machine!

Is there an article, blog post, tutorial or guide to follow for enabling the client app on linux?

Thank you

**Comment by neodynamic** [comment]
Which browser is involved?

**Comment by ahsath** [comment]
Chrome

**Comment by neodynamic** [comment]
What errors are shown the Chrome Console?

**Comment by ahsath** [comment]
I just turned on my laptop and saw this
![image](https://user-images.githubusercontent.com/37009121/87069152-528a9080-c1dc-11ea-9349-b14435b0c1ad.png)



> What errors are shown the Chrome Console?

![image](https://user-images.githubusercontent.com/37009121/87069205-69c97e00-c1dc-11ea-8e49-df351b54315a.png)

**Comment by neodynamic** [comment]
Are you able to run this from Terminal?

`sudo jspm3 --reinstall-certificates`

**Comment by neodynamic** [comment]
@ahsath could you get it working?

**Comment by ahsath** [comment]
No I did not, maybe in another time, thank you

**Comment by qdelcourte** [comment]
Hi ! first time with JSPM
 
Same issue for me, but with this message:
<img src="https://user-images.githubusercontent.com/30729669/88171552-d18db900-cc1f-11ea-864c-36d0e2cb9cdd.png" width="400">

I also tried `sudo jspm3 --reinstall-certificates` and nothing changes

**Comment by neodynamic** [comment]
Thanks for the feedback... we're working on it

**Comment by neodynamic** [comment]
Please download and install the new build 3.0.20.729 from here https://www.neodynamic.com/downloads/jspm and let us know how it works now. Thanks!

**Comment by neodynamic** [comment]
Great!

**Comment by neodynamic** [comment]
> Hi there,
> 
> excuse me for commenting on a closed issue. But I have exactly the same problem running JSPM4 Client on a Raspberry Pi 4 (Raspbian OS). When running:
> `sudo jspm4 --reinstall-certificates`
> I keep getting a system alert dialog with the following error:
> 'Could not create the certificate vault'
> 
> I had no problems at all with running this on an Mac OSX.
> 
> Any suggested advice on how to get this running on Raspberry Pi 4?
> 
> Thanks.

We could reproduce the issue and a new build was just released so please try it there and let me know
https://www.neodynamic.com/downloads/jspm/jspm-4.0.21.728-armhf.deb
