### ISSUE TITLE
Where should I register my license key?

### ISSUE THREAD

**Issue by valueor** [neodynamic/JSPrintManager#13]
I bought jspm3.0, but I don't know where to register the license key. They told me to look at the product manual, but I don't know where the product manual is. help

**Comment by neodynamic** [comment]
Please refer to [https://www.neodynamic.com/Products/Help/JSPrintManager3.0/articles/license-registration.html](https://www.neodynamic.com/Products/Help/JSPrintManager3.0/articles/license-registration.html) and in case of any issues please [contact our support team](https://neodynamic.com/support)

**Comment by shibilababy** [comment]
I purchased the licence key, how  to add my licence key in our js code
