### ISSUE TITLE
JSPrintManager modifies file extensions in printer queue

### ISSUE THREAD

**Issue by tmuelli** [neodynamic/JSPrintManager#15]
Hi guys!

This is not much of an issue, as printing with JSPrintManager just works fine. 
But after confirming the final print dialog (evaluation mode) I noticed that, e.g. _MyFile.pdf_ is added as _0,1,MyFile.wpdf_ inside of printers queue. 

This is only visible with a printer, which is not connected, as otherwise its not possible to inspect the printer queue properly. 

Same happens when using the PDFCreator as DefaultPrinter. The created file is saved according to the above pattern. 

Any guesses why this is happening?
Thank you very much

**Comment by neodynamic** [comment]
Thanks for the feedback. We'll consider this for some future update.
