### ISSUE TITLE
Unstable ClientPrintJobGroup()

### ISSUE THREAD

**Issue by duyhung85** [neodynamic/JSPrintManager#16]
Hi,

I am testing JSPM on a POS system where we print bar and print kitchen in one click. 
I am using the html2canvas example to render html/css DOM to base64 png and send it to printers with JSPM.ClientPrintJobGroup() at once. It's working but sometimes the outcome text got overlaps (check the attached image). I am sure the image rendered correctly but the print outcome is not good.
I changed the solution to send to each printer separately using JSPM.ClientPrintJob() and it seems working ok for now, not 100% sure though.
![4f61263e9a0a66543f1b](https://user-images.githubusercontent.com/4004056/88778513-d10e9880-d1b2-11ea-8a9b-cc854f67eb85.jpg)
Any idea how we can fix this issue? Thanks

**Comment by neodynamic** [comment]
Please [send the source code you wrote so far to our support team](https://neodynamic.com/support)
