### ISSUE TITLE
PrintRange can exceed actual number of pages

### ISSUE THREAD

**Issue by tmuelli** [neodynamic/JSPrintManager#17]
Hi guys,

I'm trying to print a PDF file using `JSPrintManager()`.
I've got a file, which is 2 pages long. Now if I specify `myFile.printRange` with an value greater than 2 it loads the evaluation dialog and after confirming, I get an error _"Job cancelled: WPDF Invalid Page Range"_. (see Screenshot below)

My source code:
```
...
// set content to print
var myFile = new JSPM.PrintFilePDF('../files/Demo.pdf', JSPM.FileSourceType.URL, 'MyFile.pdf', 1);
if (myFile.isValidRange(range.value)) {
  myFile.printRange = range.value;

  // add file to print job
  cpj.files.push(myFile);

  // send print job to printer
  cpj.sendToClient();
} else {
  ...
}
```

![exceedprintrange](https://user-images.githubusercontent.com/44841170/88893077-18923480-d246-11ea-96a9-32b94a8c50f7.jpg)

This dialog comes right after confirming the evaluation dialog. (see below)

![eval_dialog](https://user-images.githubusercontent.com/44841170/88893138-352e6c80-d246-11ea-8f32-b4dbd608ea4c.jpg)

Is there a way to get the number of pages from the `myFile` object?

Thank you!

**Comment by neodynamic** [comment]
JSPrintManager does not provide such feature but you could try [PDF.js](https://github.com/mozilla/pdf.js) to [get the total number of pages from a pdf file](https://stackoverflow.com/a/29481391) and then set a valid page range to the PrintFilePDF object.

Now, yes, we see that behavior on JSPrintManager when the page range is invalid, the error dialog appears but the printing process continues and this is something we'll review and fix in the next maintenance release. Meanwhile, see if the above workaround is something you can consider to do.

**Comment by tmuelli** [comment]
Thank you very much for the response.
Your considered workaround gets the job done.

Though when this bug is being fixed, I assume there is no need to include PDF.js (and its dependencies) anymore, as JSPrintManager then handles invalid page ranges on its own?

**Comment by neodynamic** [comment]
I see now that you're using v2.0 not the latest v3.0
Sadly, V2.0 will not be updated any longer. The update will be applied on V3.0 as the issue is in latest version as well
If we make that JSPrintManager behaves the same way as Adobe Reader or Foxit, then if the print range is invalid, the print job should be cancelled.

**Comment by tmuelli** [comment]
I am using v3. The screen which I provided was made earlier.
Anyway thank you very much for your help.
