### ISSUE TITLE
Uncaught (in promise) Malformed message

### ISSUE THREAD

**Issue by duyhung85** [neodynamic/JSPrintManager#18]
Hi,

I am having this error message in console when load up jsprintmanager:
`JSPrintManager.js:980 Uncaught (in promise) Malformed message. Error: { "id" : "a1920acd", "type" : "message", "last" : true }`
The lib is still working though but I dont know why its showing up this error message

Please help,
Hungnd

**Comment by neodynamic** [comment]
If possible, might you send us the message sent from JS with that same ID?

**Comment by duyhung85** [comment]
Hi,

Thank you for your reply. Here is the screenshot details of the error:

<img width="1278" alt="Screen Shot 2020-08-06 at 9 06 00 AM" src="https://user-images.githubusercontent.com/4004056/89482508-45a19280-d7c4-11ea-9f11-719c6b0e753b.png">

**Comment by neodynamic** [comment]
Please update [JSPrintManager.js](https://github.com/neodynamic/JSPrintManager/blob/master/scripts/JSPrintManager.js)
