### ISSUE TITLE
Is there any pure JavaScript library available to print without chrome print dialog?

### ISSUE THREAD

**Issue by kamran-jabbar** [neodynamic/JSPrintManager#2]
I see your application is in some JS framework, 
I want to do it in pure javascript. 
Any help will be appreciated.
Thanks

**Comment by neodynamic** [comment]
JSPrintManager is pure javascript code that does not require any special framework!
To perform advanced client side printing from javascript, our JSPrintSolution also requires [each client to install a small utility that also does not require any framework](https://neodynamic.com/downloads/jspm). Our solution allows printing from Javascript to Windows, Linux, Mac and Raspberry Pi client devices
