### ISSUE TITLE
Printing orientation

### ISSUE THREAD

**Issue by pparedesam** [neodynamic/JSPrintManager#20]
I am trying to change the orientation with ESC T n, but "n" is two numbers separated from a ",", for example "1,49" and I am defining it like this: 
```

var esc = '\ x1B T 1,49';
var cmds = esc + "@";
```

this is the way to change the orientation, since the printer keeps printing the same or is there another way to define it to do it, since I need to do it Bottom to top.

I would appreciate you can help me.

**Comment by neodynamic** [comment]
Hi, we don't provide printer commands support. A quick web search will tell you that the correct command for orientation seems to be ESC V 1 i.e. `\x1BV\x01`

**Comment by pparedesam** [comment]
Thank! 

Regarding JSPM.PrintFileTXT it does not support double spaces when creating the text file, it has been tested and there is no way to create a tab or double space. 

`
 var my_file = new JSPM.PrintFileTXT("    Hola         Mundo        ", 'MyFile.txt', 1);
`
Just interpret "Hola Mundo" without spaces

**Comment by neodynamic** [comment]
Try setting the TextAlignment prop to None

`my_file.textAlignment = JSPM.TextAlignment.None;`
