### ISSUE TITLE
RAW Printing

### ISSUE THREAD

**Issue by shyamsamtan** [neodynamic/JSPrintManager#22]
How to cut the paper automatically after printing the data on paper in thermal printers.
I am testing in BIXOLON SRP-332II.
Is their any command to do it? Please help me. Thanks in advance

**Comment by shyamsamtan** [comment]
Printer can be of any company but it supports the cut function.

**Comment by neodynamic** [comment]
Please look at [this printer manufacturer website](https://www.bixolon.com/download_view.php?idx=25#download-anchor05). Download the **Command Manual_SRP-330II** pdf and refer to the CUT command syntax.
