### ISSUE TITLE
Uncaught (in promise) zip.js, zip-ext.js, and deflate.js files from https://github.com/gildas-lormeau/zip.js project are missing.

### ISSUE THREAD

**Issue by tdegrunt** [neodynamic/JSPrintManager#24]
I'm trying to add JSPrintManager to our project. I've added jsprintmanager to our package.json:

```
  "dependencies": {
    "@zip.js/zip.js": "^2.2.16",
    "jsprintmanager": "^3.0.6",
  },
```

I've also added zip.js, but JSPrintManager keeps on complaining that I need to add zip.js, zip-ext.js, and deflate.js files.

Any suggestions as to how to fix this? I'm trying to use webpack with npm/yarn as much as possible, adding these files to our html like suggested is not really an option.

**Comment by tdegrunt** [comment]
After reading more on zip.js, some things start working when I use this instead:
```
import * as zip from "@zip.js/zip.js/dist/zip-fs-full.min.js"
window.zip = zip
```

But this zip.js is probably not compatible with JSPrintManager?

**Comment by Irykson** [comment]
We had the same problem. The zip.createWriter is removed from version 2.x (see issue: https://github.com/gildas-lormeau/zip.js/issues/220#issuecomment-778484382). Prior versions are not published as a npm-package.

Unless @neodynamic updates JSPrintManager to use this version you have to manually add the old one to your project.
I know of two options here:
1. Manually install the last commit with the old structure:
`npm i git+https://github.com/gildas-lormeau/zip.js.git#3e7920810f63d5057ef6028833243105521da369`
2. Copy the files from this repo and use them.

But I've not checked, if you can now use it with WebPack via an import. We're using a plugin to add the files as a script tag to our index.html.

**Comment by tdegrunt** [comment]
Thanks for your comment!
Eventually we added these files to a vendor folder and included them using:

```
import "imports-loader?wrapper=window!../vendor/zip.js"
import "imports-loader?wrapper=window!../vendor/zip-ext.js"
import "imports-loader?wrapper=window!../vendor/deflate.js"
```

You should excluded them from babel-loader using:

```
        exclude: /(node_modules|bower_components|zip|zip-ext|deflate)/,
```

That seems to work (for us).

**Comment by neodynamic** [comment]
Thanks for reporting this issue. We've just updated our package to support zip.js v2. The new package version is 3.0.7
Be sure you ref to zip-full js file 

```
import * as zip from "@zip.js/zip.js/dist/zip-full.min.js"
window.zip = zip
```
