### ISSUE TITLE
Handshake Mode does not cover all cases.

### ISSUE THREAD

**Issue by qntbkk** [neodynamic/JSPrintManager#26]
I have try to print raw command with sp40 plus. The buffer control in this passbook printer is DTR+SRTS, and using finanacial ibm = honorCTS. It does not print out anything, look like the jsprintmanager has a limit of handshake mode 

None
RequestToSend
RequestToSendXOnXOff
XOnXOff

When i change the printer handshake to xonxoff, then it can able to print out.

How i can add a custom handshake into jsprintmanager ?

Thanks

**Comment by neodynamic** [comment]
Please try the new update https://github.com/neodynamic/JSPrintManager/blob/master/scripts/JSPrintManager.js and be sure you download and install the latest JSPrintManager client App https://www.neodynamic.com/downloads/jspm/
