### ISSUE TITLE
Unhandled rejection Malformed message. 

### ISSUE THREAD

**Issue by pondpaun7z** [neodynamic/JSPrintManager#28]
after i scan i didn't get data and get some error

```
Unhandled rejection Malformed message. Error: TypeError: blob.slice(...).arrayBuffer is not a function Message: [object Blob]
```

![Screen Shot 2564-05-11 at 22 58 47](https://user-images.githubusercontent.com/9154252/117847458-8f1b9280-b2ac-11eb-9097-8e10c475ddf5.png)

**Comment by pondpaun7z** [comment]
@neodynamic  Yes still get same error
my JSPrintManager.js  version is v3.0.8 and JSPrintManager clien app version 3 is installed

I run in Electron app
My print model is "Brother MFC-T810W"

**Comment by neodynamic** [comment]
Two problems

1. Current version does not support Electron apps
2. If you do not get anything from the scan job, then it could be a problem related to the driver. In the next version 4.0 we'll be shipping a new scanning process

**Comment by pondpaun7z** [comment]
@neodynamic  Thank you.
I think it's not support Electron apps.
I try on Vue web. Its work
