### ISSUE TITLE
Scanner not working when scan on second times.

### ISSUE THREAD

**Issue by pondpaun7z** [neodynamic/JSPrintManager#29]
When i scanner first time it worked but i click scan again it's not working.
i found same issue on https://jsprintmanager.azurewebsites.net/

i think printer still running after scanned

I dont know it's relate about printer model?

My printer is `Brother MFC-T810W`

**Comment by neodynamic** [comment]
Hi,

A preview of V4 which is shipped with new scanner support based on TWAIN API is available. 

1. Download and install v4 client app from here
https://neodynamic.com/temp/jspm-4.0.0.0-win.exe

2. You can test the new TWAIN scanner support in the V4 demo which is available here
https://jspmdemo.azurewebsites.net/

Let us know if issue persists. Thanks,

**Comment by pondpaun7z** [comment]
@neodynamic  I used MacOS. have jspm 4.0 for Mac?

**Comment by neodynamic** [comment]
No, but v4 will be released in about 10 days. Was the original issue in macOS?

**Comment by pondpaun7z** [comment]
@neodynamic 
Printer still running after scanning done. it affect can't scanning second time

**Comment by pondpaun7z** [comment]
@neodynamic 
And i found same problem on https://jsprintmanager.azurewebsites.net/ and window and another printer

**Comment by pondpaun7z** [comment]
@neodynamic  Scanning not working on JSPM version 4

**Comment by jason09** [comment]
> 
> 
> @neodynamic Scanning not working on JSPM version 4
same issue. finally using JSPM version 3

**Comment by neodynamic** [comment]
> > @neodynamic Scanning not working on JSPM version 4
> > same issue. finally using JSPM version 3

V4 no longer uses WIA drivers but TWAIN so... is your scanner installed with a TWAIN compatible driver?

**Comment by jason09** [comment]
> 
> 
> > > @neodynamic Scanning not working on JSPM version 4
> > > same issue. finally using JSPM version 3
> 
> V4 no longer uses WIA drivers but TWAIN so... is your scanner installed with a TWAIN compatible driver?

i'm using Canon CanoScan LiDE 300
i downloaded TWAIN-compliant scanner driver from here: https://asia.canon/en/support/0100963601
but still not working.

**Comment by neodynamic** [comment]
> > > > @neodynamic Scanning not working on JSPM version 4
> > > > same issue. finally using JSPM version 3
> > 
> > 
> > V4 no longer uses WIA drivers but TWAIN so... is your scanner installed with a TWAIN compatible driver?
> 
> i'm using Canon CanoScan LiDE 300
> i downloaded TWAIN-compliant scanner driver from here: https://asia.canon/en/support/0100963601
> but still not working.

What OS is involved?

**Comment by jason09** [comment]
> 
> 
> > > > > @neodynamic Scanning not working on JSPM version 4
> > > > > same issue. finally using JSPM version 3
> > > 
> > > 
> > > V4 no longer uses WIA drivers but TWAIN so... is your scanner installed with a TWAIN compatible driver?
> > 
> > 
> > i'm using Canon CanoScan LiDE 300
> > i downloaded TWAIN-compliant scanner driver from here: https://asia.canon/en/support/0100963601
> > but still not working.
> 
> What OS is involved?

Window 10 64bit

**Comment by neodynamic** [comment]
We had an issue with a Xerox scanner here in Windows 10 as well but after installing the correct software driver from the manufacturer and configured it to use TWAIN, then it worked just fine. We don't have a Cannon scanner here but if it provides a TWAIN driver then it should work. Be sure you set up TWAIN instead of WIA if this is allowed (contact the manufacturer website)
