### ISSUE TITLE
Temp Files Not Removed

### ISSUE THREAD

**Issue by NicoFeliceEUROTECH** [neodynamic/JSPrintManager#3]
Hi,

When i execute "new JSPM.PrintFile("NAME_FILE", JSPM.FileSourceType.URL, 'MyFile.bmp', 1)" a new folder and file are generated on client side (Temp Folder) but aren't never removed.
Is this an issue? Can delete these temps file after the .sendToClient action perform (by the script provided by you)?

Thanks in advice,
Nico

**Comment by neodynamic** [comment]
Hi, thanks for the feedback. It's not a bug. We cannot delete files that our tool cannot handle printing directly like office docs. Anyway, we'll try to do something on this matter in next versions.

**Comment by NicoFeliceEUROTECH** [comment]
Hi,

Thanks for the feedback!

**Comment by neodynamic** [comment]
This was improved in V3
