### ISSUE TITLE
JsPrintManager can't scanning on second time

### ISSUE THREAD

**Issue by pondpaun7z** [neodynamic/JSPrintManager#30]
When I scaning on first time it worked but i click scan again it's not working.i found same issue on https://jsprintmanager.azurewebsites.net/

Issue is Scanner still working after scanned on first name

**Comment by pondpaun7z** [comment]
![2564-06-17 21 02 43](https://user-images.githubusercontent.com/9154252/122412110-80ad4e80-cfaf-11eb-8c3d-7e716482e91e.gif)

**Comment by pondpaun7z** [comment]
@neodynamic But JSPrinter Client version 3.0.21.601  on window  not have  this issue

I found in Client app  version 3.0.21.425  on Mac

**Comment by neodynamic** [comment]
V4 was released... please try it and report any issues to https://neodynamic.com/support
