### ISSUE TITLE
JSPM3 on Arch or Manjaro

### ISSUE THREAD

**Issue by deikatsuo** [neodynamic/JSPrintManager#31]
I managed to install jspm3 on manjaro (by converting .deb into arch package) but it seem jspm3 not working as expected, after the popup it said need to install libre office. So after installing libre office, the popup said printing but nothing being printed on my printer.

**Comment by neodynamic** [comment]
What kind of file are you trying to print?

**Comment by deikatsuo** [comment]
> What kind of file are you trying to print?

the one in the test page

**Comment by neodynamic** [comment]
> > What kind of file are you trying to print?
> 
> the one in the test page

OK but what exact content? Raw commands requires the printer to be configured to correctly handle them. And what about printing an image or pdf?

**Comment by deikatsuo** [comment]
> > > What kind of file are you trying to print?
> > 
> > 
> > the one in the test page
> 
> OK but what exact content? Raw commands requires the printer to be configured to correctly handle them. And what about printing an image or pdf?

Just simple .jpg and .xls, neither worked.
No problem when printing .jpg using default firefox print feature

**Comment by deikatsuo** [comment]
> > > What kind of file are you trying to print?
> > 
> > 
> > the one in the test page
> 
> OK but what exact content? Raw commands requires the printer to be configured to correctly handle them. And what about printing an image or pdf?

Just simple .jpg and .xls, neither worked.
No problem when printing .jpg using default firefox print feature

**Comment by deikatsuo** [comment]
```js
await workbook.outputAsync("base64").then(function (base64) {
                if (_this.os == "#Windows") {
                  var printData = new JSPM.PrintFileXLS(base64, JSPM.FileSourceType.Base64, `receipt#${receipt.ID} ${_this.order.Customer.Code} ${_this.order.Customer.Name}.xlsx`, 1);
                  printData.pageFrom = 1;
                  printData.pageTo = 1;
                } else {
                  var printData = new JSPM.PrintFile(base64, JSPM.FileSourceType.Base64, `receipt#${receipt.ID} ${_this.order.Customer.Code} ${_this.order.Customer.Name}.xlsx`, 1);
                }

                // location.href = "data:" + XlsxPopulate.MIME_TYPE + ";base64," + base64;

                // Tambahkan file ke daftar yang akan di print
                printer.files.push(printData);
              });
```
This code worked fine on windows, but not on linux

**Comment by neodynamic** [comment]
We've just tested your scenario. We used our latest V4 not V3. We did the following

1. installed manjaro (xfce 21, linux 5.10.53-1)
2. then installed the following packages `pacman -S libreoffice cups freeimage sane` (libreoffice-fresh-7.1.5-1)
3. then we converted our [jsmp deb installer](https://www.neodynamic.com/downloads/jspm/jspm-4.0.0.0-amd64.deb) to arch with debtap and after that, we installed the arch package
4. we went to the online demo https://jsprintmanager.azurewebsites.net and tested the **Print Images & Docs** with an xls file from here https://neodynamic.com/temp/Project-Scheduling-Monitoring-Tool.xls
5. the file was printed just fine

**Comment by deikatsuo** [comment]
> We've just tested your scenario. We used our latest V4 not V3. We did the following
> 
>     1. installed manjaro (xfce 21, linux 5.10.53-1)
> 
>     2. then installed the following packages `pacman -S libreoffice cups freeimage sane` (libreoffice-fresh-7.1.5-1)
> 
>     3. then we converted our [jsmp deb installer](https://www.neodynamic.com/downloads/jspm/jspm-4.0.0.0-amd64.deb) to arch with debtap and after that, we installed the arch package
> 
>     4. we went to the online demo https://jsprintmanager.azurewebsites.net and tested the **Print Images & Docs** with an xls file from here https://neodynamic.com/temp/Project-Scheduling-Monitoring-Tool.xls
> 
>     5. the file was printed just fine

Thanks for the reply, I am have not tried V4 yet
