### ISSUE TITLE
jspm3.exe in RDS environment

### ISSUE THREAD

**Issue by jbinette-ms** [neodynamic/JSPrintManager#34]
Hi,

We have a problem with jspm3.exe, for the services daemon all is good, but for the jspm3.exe, only one user can open it, the other user have a grey icon with "waiting for port 23443 to be ready"

I understand that port cannot be ready more than 1 time in a single machine? Any solution to have JSPrintManager working in RDS Environnement? Thank you.

PS : We have to use V3, because the supplier using that on his webpage use V3.

Thank you for your help :)

**Comment by neodynamic** [comment]
RDS is not supported
