### ISSUE TITLE
How to install jspm4-4.0.21.1102-win64.msi via SCCM?

### ISSUE THREAD

**Issue by ii-batman** [neodynamic/JSPrintManager#35]
Hi
Trying to install jspm4-4.0.21.1102-win64.msi via SCCM with: `msiexec.exe" /i "jspm4-4.0.21.1102-win64.msi" PROPERTY=RUNATSTARTUP /qn`
but the app does not startup after reboot which will cause the website not see the app running.
Is there a way around this as I need to test deployment in prep for user mass deployment?
Thanks

**Comment by neodynamic** [comment]
That msi package if installed "manually", it makes the JSPM app to start at system startup. We don't have experience with SCCM so cannot tell you why that's not working out.

**Comment by ii-batman** [comment]
@neodynamic 
Pretty fast to close 🥇 but would you be able to assist on the switches and settings configured on the MSI?
If I need to deploy the app to more than a few machines I will not go one by one and run the MSI so I need to use and enterprise deployment tool like SCCM - I think this is a fair question no?

### Using Orca I can see that this setting on the MSI:
_- Feature Components_ : **MainProgram	RunAtStartup**
_- Registry:_ **reg7DF311AD7F66CFFD4753CACB5A0005D2	1	Software\Microsoft\Windows\CurrentVersion\Run	JSPrintManager 4.0 for Windows	"[#jspm4]"	RunAtStartup**

### In SCCM I an deploying the MSI with this command:
**msiexec /i "jspm4-4.0.21.1102-win64.msi" PROPERTY=RUNATSTARTUP /qn**

Do I need another PROPERTY and if so what is the value?

I appreciate your help on this matter, I really and I really want to start using this app.
Many thanks

**Comment by neodynamic** [comment]
If we run this

`msiexec /i "jspm4-4.0.21.1102-win64.msi" /qn`

The product installs and after a system restart, the JSPM app runs at startup without any issues

**Comment by ii-batman** [comment]
Brill, I got it to work using:
_`msiexec /i "jspm4-4.0.21.1102-win64.msi" PROPERTY=RUNATSTARTUP /qn`_
- Set the installation behaviour = "install for user"
- Rebooted the machine and the app starts up fine.
Thanks for your help!
