### ISSUE TITLE
How to prevent the Chrome popup when printing?

### ISSUE THREAD

**Issue by ii-batman** [neodynamic/JSPrintManager#36]
I got this pop msg when I was testing via https://jsprintmanager.azurewebsites.net/
We would like users to be able to print without being prompted.
Is there a setting which can be set using group policy on Win10 machines to prevent this pop up?
![PopUp](https://user-images.githubusercontent.com/60931858/144251730-c53fc763-42a8-4a25-ae4d-1387526951cd.PNG)

**Comment by neodynamic** [comment]
That dialog can be disabled by the user by checking the _**Don't ask again for this site**_
If you have control on those clients machines, then you can edit the `C:\Users\[USER_NAME]\AppData\Local\.neodynamic\jspmallow_list` file and add the `jsprintmanager.azurewebsites.net` entry or any other one

**Comment by ii-batman** [comment]
Awesome, do you know of a way of doing this using group policies?

**Comment by neodynamic** [comment]
No, sorry

**Comment by ii-batman** [comment]
Cool, thanks - If I find a way I be sure to post here also.
