### ISSUE TITLE
Does this package allow me to remotly print?

### ISSUE THREAD

**Issue by Attacler** [neodynamic/JSPrintManager#38]
Does this package allow me to remotely print?

Basicly my end goal is that someone can press a button on a tablet and that it gives a print command towards the printer.
I tried the Vue example but it did not work on my tablet (on pc it worked fine, with the client installed).

Does someone know a good way to fix this?

**Comment by neodynamic** [comment]
Refer to [this article](https://www.neodynamic.com/articles/How-to-print-raw-commands-pdf-files-from-iOS-Android-ChromeOS-sandboxed-devices-from-Javascript) about printing from tablet devices
