### ISSUE TITLE
can't use in react

### ISSUE THREAD

**Issue by sogatanco** [neodynamic/JSPrintManager#46]
I try use JSPrintManager in reactjs app. I just added model using `npm` then import it `import JSPM from 'jsprintmanager'` but when I call `JSPM.JSPrintManager` I get this error
![Screen Shot 2022-05-24 at 10 00 41](https://user-images.githubusercontent.com/38104669/169940041-eabe42ec-5ced-428d-8260-776053d2279e.png)

thank you

**Comment by neodynamic** [comment]
Please try `import * as JSPM from 'jsprintmanager'` instead

**Comment by developers-veintestech** [comment]
![image](https://user-images.githubusercontent.com/85544538/218815674-7af75bf8-f6b1-45eb-9ead-a3818ff0eac5.png)
`    componentDidMount() {
        JSPM.JSPrintManager.Caller = this;
        //get client installed scanners
        JSPM.JSPrintManager.getScanners().then(function (scannersList) {
            JSPM.JSPrintManager.Caller.setScannerDevices(scannersList);
        });
    }
`
Getting JSPM undefiend
