### ISSUE TITLE
Demo Print Images & Docs fails to print PDF

### ISSUE THREAD

**Issue by nelwa** [neodynamic/JSPrintManager#50]
Hi,

The **Demo** for **Print Images & Docs** fails to print the provided sample pdf, or any local pdf.

For the sample pdf (https://neodynamic.com/temp/LoremIpsum.pdf) I receive this error: "**Job cancelled: An operating system call failed.**" - this is shown in the Job Trace window: > {}

For any local pdf I receive this error: "**Job cancelled: System error, (OS Code 2):
No such file or directory.**"  The error is produced for any pdf in any directory on my local system.  I have tried lots of different options, home directory, downloads directory, root directory, even used files with 777 permissions.  All produce the same error.  Nothing is shown in the job trace window.

In any of the above cases, when not clicking Ok on the produced error alert but anywhere else, the alert disappears and the jspm5 client needs to be restarted for anything further to work.

The same problem occurs on the **Advanced PDF Printing** demo.

The **Raw Data Printing** demo works correctly.

I'm using jspm5 (latest version) on Linux Mint.

Please let me know what I'm doing wrong.

Thanks

**Comment by neodynamic** [comment]
Please download and install build 5.0.22.1110 from here https://www.neodynamic.com/downloads/jspm/ and let us know

Thanks,
