### ISSUE TITLE
JSPM Job cancelled error

### ISSUE THREAD

**Issue by saadimam01** [neodynamic/JSPrintManager#51]
Each time after a few prints JSPM raises an error that the job canceled list index (4) out of bounds. Attaching the image for reference.

![Neodynamics](https://user-images.githubusercontent.com/93452379/196114871-845347f5-e495-48c9-a421-5a7056312fdd.jpeg)

**Comment by belxiors** [comment]
I have the same issue. Did you get any info from support about this?

**Comment by Ronjea** [comment]
I have the same issue here any news on that one ?
