### ISSUE TITLE
Unhandled rejection Access violation

### ISSUE THREAD

**Issue by atlet** [neodynamic/JSPrintManager#52]
I'm using Ubuntu Linux. I installed JSPM5 client and tried scanning a document from your demo, but I get error "Unhandled rejection Access violation". I written two times to your support email and contact form 14 days ago, but till today I didn't received any answer. 

I tried the same from Windows and it's forking fine. Any idea how can I make this example working from Linux?

**Comment by neodynamic** [comment]
Please download and install build 5.0.22.1110 from here https://www.neodynamic.com/downloads/jspm/ and let us know

Thanks,

**Comment by atlet** [comment]
Still the same error with this version.

**Comment by neodynamic** [comment]
Try PNG output instead of JPG and let us know

**Comment by atlet** [comment]
Also with PNG I get the same error. :( Is there a way to see more data of error? Si I can help you debug.

**Comment by neodynamic** [comment]
We recommend you to upgrade to the latest V7 which includes many fixes. Re open this issue if it persists after upgrading. Thanks!
