### ISSUE TITLE
Printers Info not get real (false) info

### ISSUE THREAD

**Issue by 1TCP5** [neodynamic/JSPrintManager#53]
I try to get printer info as guide here (https://www.neodynamic.com/Products/Help/JSPrintManager5.0/articles/jsprintmanager.html#get-installed-printers-including-detailed-information), 
but the status always wrong, is connected always true

**Comment by neodynamic** [comment]
The latest V7 build from our website https://www.neodynamic.com/downloads/jspm has improved it
