### ISSUE TITLE
Define Job Name in windows printer  job queue screen

### ISSUE THREAD

**Issue by michel-soares** [neodynamic/JSPrintManager#54]
Can we define the name of the print that show in printer jobs screen queue on windows SO machine?

![image](https://user-images.githubusercontent.com/14979508/218762005-e320eb83-fa06-46b9-bd85-45b588cd9c68.png)

**Comment by neodynamic** [comment]
The latest V7 allows you to specify it through this new prop https://www.neodynamic.com/Products/Help/JSPrintManager7.0/apiref/classes/ClientPrintJob.ClientPrintJob-1.html#printerCommandsDocName
