### ISSUE TITLE
WebSocket connection to 'wss://ip(234)-:25443/' failed: 

### ISSUE THREAD

**Issue by amaliraza** [neodynamic/JSPrintManager#56]
Dear Concerns,
I want to use Js Print Manager for my client project but I am facing a websocket connection failure error (kind see attached images).

I have installed the JSPM App On IP (###.###.###.234) and 
deployed my project on IP (###.###.###.192) both are local IPs and are on the same network.

I have added script link for jsprintmanager.js on my layout.cshtml file and added below lines in layout file 

JSPM.JSPrintManager.auto_reconnect = true;
JSPM.JSPrintManager.start(true, '###.###.###.234', 25443);

I have also allowed port(25443) from firewall advanced settings (inbound/outbound)
but still facing websocket errors.

Kindly guide me on how I can get rid of this issue.

**Comment by ster** [comment]
solved.

i run the Js Print Manager from command line with the command: /usr/bin/jspm5 and it works

**Comment by amaliraza** [comment]
> Hi ! did you solve it?

Yes, I had solved it.
I just need to change the location of certificate on client machine.
It should be under "Trusted Root Certifications Authorities"

**Comment by thaneshhoneybill** [comment]
> > Hi ! did you solve it?
> 
> Yes, I had solved it. I just need to change the location of certificate on client machine. It should be under "Trusted Root Certifications Authorities"

hii

how to solve this issue
