### ISSUE TITLE
Firefox cannot connect to the server ws://localhost:26443/.

### ISSUE THREAD

**Issue by shade7g** [neodynamic/JSPrintManager#61]
I try to use "ws://" instead of "wss://" but it doesn't work for some reason
When I use "wss://" everything works just fine so I'm sure the issue isn't related to my app

"JSPM.JSPrintManager.start(false, "localhost", 26443);", I use jspm6

Output given:
"Firefox cannot connect to the server ws://localhost:26443/."
"NS_ERROR_WEBSOCKET_CONNECTION_REFUSED"

**Comment by neodynamic** [comment]
WSS is the only supported now.
