### ISSUE TITLE
JSPM 6 will not print

### ISSUE THREAD

**Issue by Inbasecom** [neodynamic/JSPrintManager#64]
The print job is fired, the printer is not working.
`
if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Open)
{
    var my_file  = new JSPM.PrintFilePDF('/path/file.pdf', JSPM.FileSourceType.URL, 'file.pdf', 1);
    var cpj      = new JSPM.ClientPrintJob();
    cpj.clientPrinter = new JSPM.DefaultPrinter();
    cpj.files.push(my_file);
    cpj.sendToClient();
}
`
With JSPM5 everything works without any problems, with JSPM6 the printer is silent.
I get the following response on the console:
`
Promise { <state>: "pending" }​
<state>: "fulfilled"​
<value>: Object { result: "Parsing OK. Starting printing" }​​
result: "Parsing OK. Starting printing"​​
<prototype>: Object { … }​
<prototype>: Promise.prototype { … }
`

I get the following error in the client application log:
`
Number: 301513  Date: 22.01.2024 11:17:32 ID: 1003  Type: Error Category: 3 User: N/A Domain: N/A Computer: xxx-01-xx-02.xxxx.local Data: Job ID b79bdda9
Additional info: { "file" : "Testseite.pdf", "id" : -1, "description" : "Job cancelled: System error, (OS Code 193):\r\n" };
`

Am I just not seeing the error, or is there actually a problem?
(Windows 10, Firefox up to date)

**Comment by Inbasecom** [comment]
additional info:

Printing PNG images works
var my_file = new JSPM.PrintFile(....

only 
var my_file = new JSPM.PrintFilePDF(...
does not work.

**Comment by neodynamic** [comment]
Your Windows OS is 64 or 32 bits?

**Comment by Inbasecom** [comment]
Our Windows operating system is 64bit and we have installed the 32bit JSPM version to be able to scan.
The problem is solved, we have uninstalled and reinstalled the JSPM on this computer and it now works perfectly. 
We did not have this problem on other computers, so we were able to isolate the error to one PC and fix it. 

Sorry for the entry here.
