### ISSUE TITLE
Unable to import this module.

### ISSUE THREAD

**Issue by SnapeEye** [neodynamic/JSPrintManager#7]
Hello, guys!

You published this module on https://www.npmjs.com/
https://www.npmjs.com/package/jsprintmanager

But the downloaded file has no export of the JSPM instance. As I understand, the downloaded module has no access to its functionality.

You should create extra file for npm module, that will contain all the code from JSPrintManager.js and additional row at the end of the file:
`module.exports = JSPM;`

Or, at least, set your instance in window:
`window.JSPM = JSPM;`

Is it possible for you to implement this?

**Comment by neodynamic** [comment]
Thanks @SnapeEye for the feedback. A new build was released with those additions. Please update it and let us know.

**Comment by SnapeEye** [comment]
@neodynamic works perfectly!
Thank you so much for fast response!

**Comment by qdelcourte** [comment]
Hi ! Need to reopen this issue

Why the functionality has disappeared from V3 ?

See commit https://github.com/neodynamic/JSPrintManager/commit/7d816949edabaa4d34cad86c82015ed0f6e95474 in JSPrintManager.js from L1176 to L1184

**Comment by neodynamic** [comment]
Thanks for your feedback! Please try the new script https://github.com/neodynamic/JSPrintManager/blob/master/scripts/JSPrintManager.js

**Comment by qdelcourte** [comment]
It works :) 
Thanks for the fix!
