### ISSUE TITLE
Encoding for raw printing

### ISSUE THREAD

**Issue by SnapeEye** [neodynamic/JSPrintManager#8]
Hello, guys!

Is there any API to set custom encoding for raw data printing?
Because I get strange symbols as result if I send symbols from CP-1251 encoding (for example).

This issue can be solved by printing a TXT file, but it's printed only within 50% of the paper size...

Could you, please, give some advises or solutions to solve this issue?

**Comment by neodynamic** [comment]
Which commands are you trying to send to the printer? Please provide a complete source code to reproduce it

**Comment by SnapeEye** [comment]
Code sample for raw printing with CP-1251 data:

`function getPrinterData() {
    // use this commands to create the message
    const init = '\x1B' + '\x40';
    const encoding = '\x4B' + '\x4F' + '\x49' + '\x38' + '\x2D' + '\x55';
    const leftAlign = '\x1B' + '\x61' + '\x30';
    const centerAlign = '\x1B' + '\x61' + '\x31';
    const rightAlign = '\x1B' + '\x61' + '\x32';
    const full = '\x1B' + '\x61' + '\x33';
    const lineBreak = '\x0A';
    const boldOn = '\x1B' + '\x45' + '\x0D';
    const boldOff = '\x1B' + '\x45' + '\x0A';
    const doubleFontSize = '\x1D' + '\x21' + '\x11';
    const standartFontSize = '\x1D' + '\x21' + '\x00';
    const emOn = '\x1B' + '\x21' + '\x30';
    const emOff = '\x1B' + '\x21' + '\x0A' + '\x1B' + '\x45' + '\x0A';
    const smallText = '\x1B' + '\x4D' + '\x31';
    const normalText = '\x1B' + '\x4D' + '\x30';
    const cutPaper = '\x1B' + '\x69';

    const message =
init + 
encoding +
centerAlign +
'ФОП исполнитель' + lineBreak +
'Магазин Название' + lineBreak +
'вул. Адрес 123' + lineBreak +
boldOn +
'ІПН: 123456789 + lineBreak +
boldOff +
'Номер чека: 1' + lineBreak +
lineBreak;

    return message;
}

const printInstance = new JSPM.ClientPrintJob();

printInstance.clientPrinter = new JSPM.InstalledPrinter('POS-58-Series', false, '', '');

printInstance.printerCommands = getPrinterData();

printInstance.sendToClient();`

Using this code, I get result with big paddings (top/bottom).

**Comment by SnapeEye** [comment]
When I try to send a complete example as a TXT file, my formatting is skipped:
`
const printInstance = new JSPM.ClientPrintJob();

printInstance.clientPrinter = new JSPM.InstalledPrinter('POS-58-Series', false, '', '');

const output = '                 Чек №2                 \n          Дякуємо за покупку!          ';

const myTxtFile = new JSPM.PrintFileTXT(output, 'test.txt', 1);

// if keep default padding - content doesn't fit
// if remove it - text alignment is damaged somehow
myTxtFile.marginTop = 0;
myTxtFile.marginRight = 0;
myTxtFile.marginBottom = 0;
myTxtFile.marginLeft = 0;
printInstance.files.push(myTxtFile);

printInstance.sendToClient();
`

**Comment by neodynamic** [comment]
To use a specific codepage for raw commands, we need to convert them with the help of another tool. In the sample below, we'll use the project [https://github.com/SheetJS/js-codepage](https://github.com/SheetJS/js-codepage) for that conversion. 

1. Download the **cptable.js** and **cputils.js** files from that repo and add it to your project. Then reference them through the `script` tag

2. Then you can convert the commands generated by your `getPrinterData()` using the Codepage 1251 as follows. Notice you must set the **binaryPrinterCommands** instead of _printerCommands_ property

```js
const printInstance = new JSPM.ClientPrintJob();

printInstance.clientPrinter = new JSPM.InstalledPrinter('POS-58-Series', false, '', '');

//Set printer binary commands...
var binCmds = new Uint8Array(cptable.utils.encode(1251, getPrinterData()));
printInstance.binaryPrinterCommands = binCmds;

printInstance.sendToClient();
```

Try it and let us know how it works.

**Comment by SnapeEye** [comment]
Sorry for long response.

Tried your code example. It printed 1 of 3 times only (2 tries were skipped, maybe the problem is in my code...).
But the result is wrong even with correct enoding, anyway.

I used npm module esc-pos-encoder (https://www.npmjs.com/package/esc-pos-encoder).
The encoding I chose: cp-866 (it has problems with 2-3 signs, but it can be fixed in code).
The result was perfect.

Anyway, thanks for your help!

**Comment by neodynamic** [comment]
So may you clarify if you had to use that other module to generate the ESP/POS commands and then specify them to our product?

**Comment by SnapeEye** [comment]
I used the other module because I didn't get the result I needed.

cp-866, cp1251 encoding gave me the wrong result using your utils (I need valid Cyrillic text representation). Also, I had to press my 'print' button 3-4 times to get printed output (don't have such behavour with my module).

My module has lots of usefull benefits, like text formatting, setting text align and, the most valuable for me, encoding. It supports not so many encodings, but cp-866 suited me perfeclty.

**Comment by neodynamic** [comment]
If possible send us the commands (if they are different from the provided earlier) you wanted to print so we can see what's going on with those encoding tables. Thanks.

**Comment by SnapeEye** [comment]
`
const printInstance = new JSPM.ClientPrintJob();
printInstance.clientPrinter = new JSPM.InstalledPrinter('POS-58-Series', false, '', '');

const data = new Uint8Array(cptable.utils.encode(866, 'ТЕСТ ІіЇїЄє'));
printInstance.binaryPrinterCommands = data ;

printInstance.sendToClient();
`

**Comment by neodynamic** [comment]
What we see is that the `Іі` chars are not part of [CodePage 866](https://wikivisually.com/wiki/Code_page_866) and that's why they are converted to 0 byte values 

```js
new Uint8Array(cptable.utils.encode(866, 'ТЕСТ ІіЇїЄє'));
Uint8Array(11) [146, 133, 145, 146, 32, 0, 0, 244, 245, 242, 243]
```

Those Cyrillic chars are part of [CodePage 855](https://wikivisually.com/wiki/Code_page_855) and [CodePage 1251](https://wikivisually.com/wiki/Code_page_1251) and by specifying them you'll get the correct byte values depending on the selected CodePage

```js
new Uint8Array(cptable.utils.encode(855, 'ТЕСТ ІіЇїЄє'));
Uint8Array(11) [230, 169, 228, 230, 32, 139, 138, 141, 140, 135, 134]

new Uint8Array(cptable.utils.encode(1251, 'ТЕСТ ІіЇїЄє'));
Uint8Array(11) [210, 197, 209, 210, 32, 178, 179, 175, 191, 170, 186]
```

We also see that our product is sending the converted values without any modifications so the key here is to select the correct CodePage for conversion and the same CodePage specified as a param to your printer

**Comment by SnapeEye** [comment]
I know about this _Іі_ symbol and I replace it with equal English one in js code.
I tried to generate content with 855 and 1251 encoding - result was bad.
[http://prntscr.com/qk11b5](url)
On the picture: first line - 855, second line - 1251.
Also, with your tool I have to press print button about 4 times to get result.
I don't know why, but code with my module works from the first time...

**Comment by neodynamic** [comment]
Not sure what to tell you about that. The conversions we specified earlier are correct and we have verified the bytes are sent without modifications. If that other module generates the correct commands then you should be able to send them to the printer through our product as well.

**Comment by SnapeEye** [comment]
I decided to create data with esc-pos-encoder. Using it, I get almost 100% of expected result.
Anyway, thanks for your help!
