### ISSUE TITLE
Update Readme: Add 'How to use' section

### ISSUE THREAD

**Issue by mhmdtshref** [neodynamic/JSPrintManager#9]
Hi Neodynamic!

It takes a lot of time to track the demo code to be able to use the package. What if I don't have knowledge in ReactJS ?

I think adding 'How to use' section to the readme file will be useful and will make it easier to the developers to understand how does this package work.

Thanks

**Comment by neodynamic** [comment]
Thanks a lot for your feedback. We've updated README pointing to our [Articles](https://www.neodynamic.com/products/printing/js-print-manager/articles) section which contains different printing topics with source code written in plain Javascript code
